// <auto-generated />
using System;
using CouponAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CouponAPI.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("CouponAPI.Domain.Entity.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CouponCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeCreateCoupon")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            CouponCode = "05OGA",
                            DateTimeCreateCoupon = new DateTime(2023, 4, 8, 17, 19, 11, 773, DateTimeKind.Local).AddTicks(6890),
                            DiscountAmount = 5m
                        },
                        new
                        {
                            CouponId = 2,
                            CouponCode = "09OGA",
                            DateTimeCreateCoupon = new DateTime(2023, 4, 8, 17, 19, 11, 773, DateTimeKind.Local).AddTicks(6921),
                            DiscountAmount = 9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
